- name: Include vars
  include_vars: "main.yml"

- name: "check MySQL5.6 installed"
  shell: mysql --version | cut -d ' '  -f 6 | cut -c1-4
  register: mysql_version

- name: "register MySQL installed"
  set_fact:
    MYSQL_INSTALLED : True
  when: (mysql_version.stdout == MYSQL_VERSION)
  ignore_errors: True

- name: "APT: update"
  become: yes
  apt: update_cache=yes
  when: not MYSQL_INSTALLED

- name: "APT: install MySQL5.6"
  become: yes
  apt: pkg={{ item }} state=present update_cache=yes force=yes
  with_items:
    - mysql-client-5.6
    - mysql-server-5.6
  when: not MYSQL_INSTALLED

  
