- name: Include vars
  include_vars: "main.yml"

- name: Include vars (for YUM)
  include_vars: "yum.yml"

- name: "YUM mysql5.6 install"
  become: yes
  yum: name={{ item }}
       state=present
  with_items:
    - "{{ MYSQL56_CLIENT_RPM }}"
    - "{{ MYSQL56_SERVER_RPM }}"
    - "{{ MYSQL56_SHARED_COMPAT_RPM }}"
    - "{{ MYSQL56_DEVEL_RPM }}"
