- name: "APT: update"
  become: yes
  apt: update_cache=yes
  when: not PHP_INSTALLED

- name: "APT-ADD: check apt-add-repository command"
  stat: path=/usr/bin/apt-add-repository
  register: apt_add_file

- name: "APT-ADD: install python-software-properties"
  become: yes
  apt: pkg=software-properties-common state=present
  when: not apt_add_file.stat.exists

- name: "APT: apt-add-repository"
  become: yes
  shell: >
    apt-add-repository -y ppa:ondrej/php5-5.6
  when: not PHP_INSTALLED

- name: "APT: update"
  become: yes
  apt: update_cache=yes
  when: not PHP_INSTALLED

- name: "APT: install php5.6 and apache2"
  become: yes
  apt: pkg={{ item }} force=yes
  with_items:
    - php5
    - php5-curl
    - php5-gd
    - php5-imagick
    - php5-intl
    - php5-mcrypt
    - php5-mysql
    - php-soap
    - php5-xsl
  when: not PHP_INSTALLED

- name: "check PHP5.6 installed"
  shell: php -v | head -n 1 |cut -d ' ' -f 2 | cut -c1-4
  register: php_version_new
  when: not PHP_INSTALLED

- name: "apache: enable rewrite"
  become: yes
  file: src=/etc/apache2/mods-available/rewrite.load
        dest=/etc/apache2/mods-enabled/rewrite.load
        state=link
        
- name: "apache: service restart"
  become: yes
  service: name=apache2 state=restarted
  ignore_errors: True
