- hosts: LAMP-server

  roles:
    - mysql5.6
    - apache2_php5.6
    - php5.6_mysqlbinding

  - name: "APT: install required apps"
      become: yes
      apt: pkg={{ item }} state=present update_cache=yes
      with_items:
        - git
        - mongodb
        - imagemagick
        - redis-server
        - unzip
        - g++
        - emacs
