- name: Include vars
  include_vars: "main.yml"

- name: "check PHP5.6 installed"
  shell: php --version | head -n 1 |cut -d ' ' -f 2 | cut -c1-4
  register: php_version

- name: "register PHP installed"
  set_fact:
    PHP_INSTALLED: True
  when: (php_version.stdout == PHP_VERSION)
  ignore_errors: True

# install apache2 and PHP (with apt)
- name: "check Linux distlibution(Ubuntu/Debian)"
  include: apt.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

# install apache2 and PHP (with yum)
- name: "check Linux distlibution(CentOS/RedHat)"
  include: yum.yml
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
 
- name: "check composer"
  stat: path=/usr/local/bin/composer
  register: composer_cmd
  
- name: "Install Composer"
  become: yes
  shell: >
    curl -sS https://getcomposer.org/installer | php;
    mv composer.phar /usr/local/bin/composer;
    chmod 755 /usr/local/bin/composer;
  args:
      chdir: /tmp/
  when: not composer_cmd.stat.exists
